# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

name: $(SourceBranchName)-$(Date:yyyyMMdd)$(Rev:.rrr)

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.11'
  displayName: 'Install Node.js'

- task: UsePythonVersion@0
  inputs:
    versionSpec: '2.7'
    addToPath: true
    architecture: 'x64'

- script: pip install virtualenv
  displayName: Install Virtualenv

- script: |
    npm install
    npm run e2e-test-sanitycheck:ci
  displayName: Run Sanity Checks
  
- script: |
    npm install
    npm run e2e-gui-test:ci
  displayName: Run GUI Tests